Repository carpuplay/QCM, pull requests merged in 2023-05, with the labels that each got.

#50 Add files // ian content
  content/quiz_interface/ian/config_quiz.php
  content/quiz_interface/ian/questions.html
  content/quiz_interface/ian/quiz_game.css
  content/quiz_interface/ian/quiz_game.html
  content/quiz_interface/ian/quiz_game.php
  content/quiz_interface/ian/script.js
  content/quiz_interface/ian/solo.html
  content/quiz_interface/ian/verif.php
Labels: enhancement

#54 Limitation nombre max de spe
  login/spe-select/spe-select.php
Labels: enhancement

#55 Add questions via prof
  content/quiz_interface/prof_modif/modifInterface.php
  content/quiz_interface/prof_modif/profModif.php
  login/spe-select/spe-select.php
Labels: enhancement, good first issue

#58 update alex-05-05_01 patch
  content/quiz_interface/ian/questions.html
  content/quiz_interface/prof_modif/modifInterface.css
  content/quiz_interface/prof_modif/modifInterface.php
  login/login-eleve/login.php
Labels: bug, good first issue

#62 profModif Interface and funcionality fix
  content/quiz_interface/prof_modif/modifInterface.css
  content/quiz_interface/prof_modif/modifInterface.php
  content/quiz_interface/prof_modif/profModif.php
  php-shit/php-files/verification.php
Labels: enhancement, good first issue

#66 quizz-interface and php shit fix
  content/quiz_interface/prof_modif/modifInterface.css
  login/login-eleve/login.php
  login/spe-select/spe-select.php
Labels: bug, good first issue

#69 database issues fix
  login/login-eleve/login.php
  login/login-prof/login.php
Labels: bug

#80 InterfaceModif.php fix
  README.md
  content/quiz_interface/prof_modif/modifInterface.css
  content/quiz_interface/prof_modif/modifInterface.php
  content/quiz_interface/prof_modif/profModif.php
  login/login-eleve/login.php
  login/login-prof/login.php
  login/spe-select/spe-select-prof.php
  login/spe-select/spe-select.php
  login/spe-select/wrong.css
  login/spe-select/wrong.html
  login/spe-select/wrong2.html
Labels: bug, enhancement

#83 Working on quizz interface
  README.md
  content/quiz_interface/quiz.css
  content/quiz_interface/quiz.js
  content/quiz_interface/quiz.php
Labels: bug, help wanted

#89 reorganisation and DB update
  content/dashboard/dashboard.css
  content/dashboard/dashboard.php
  content/loader/index.html
  content/loader/script.js
  content/loader/style.css
  test.sql
Labels: enhancement
